version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - worker
    networks:
      net:
        ipv4_address: 172.20.0.10
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@172.20.0.12:5672
    depends_on:
      - rabbitmq
    networks:
      net:
        ipv4_address: 172.20.0.11
  rabbitmq:
    image: rabbitmq
    ports:
      - 5673:5672
    networks:
      net:
        ipv4_address: 172.20.0.12
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@172.20.0.12:5672
      - FLOWER_PORT=8888
    ports:
      - 8889:8888
    depends_on:
      - rabbitmq
    networks:
      net:
        ipv4_address: 172.20.0.13
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1