# Generated by Django 4.1.3 on 2022-11-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_formfactor_memorytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Chipset',
                'verbose_name_plural': 'Chipsets',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('memory_slots', models.PositiveIntegerField(verbose_name='Memory Slots')),
                ('max_memory', models.PositiveIntegerField(verbose_name='Max Memory')),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motherboards', to='motherboard.chipset', verbose_name='Chipset')),
                ('form_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motherboards', to='general.formfactor', verbose_name='Form Factor')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motherboards', to='general.manufacturer', verbose_name='Manufacturer')),
                ('memory_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motherboards', to='general.memorytype', verbose_name='Memory Type')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motherboards', to='general.socket', verbose_name='Socket')),
            ],
            options={
                'verbose_name': 'Motherboard',
                'verbose_name_plural': 'Motherboards',
            },
        ),
    ]
