# Generated by Django 4.1.3 on 2022-11-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Serieses',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='Version')),
                ('cores', models.PositiveIntegerField(verbose_name='Cores')),
                ('threads', models.PositiveIntegerField(verbose_name='Threads')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpus', to='general.manufacturer', verbose_name='Manufacturer')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpus', to='cpu.series', verbose_name='Series')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpus', to='general.socket', verbose_name='Socket')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPUs',
            },
        ),
    ]
